tenant: consumers
client_id: "3ae224c9-f16c-42d1-bf5d-44151f2b99fa" # you can replace it with your own azure app for better security, but you need to create the app in portal.azure.com
local_path: "onedrive_root" # or absolute path like "/var/data/repos/onedrive_root/"
download_from_cloud: true
upload_from_local: true
sync_list_path: "" # example: "/var/data/repos/driftsync/sync_list"   # leave empty to sync everything
download_workers: 8
upload_workers: 8
upload_chunk_mb: 8
upload_parallel: 2
log:
  list_checked: true   # output details

sync:
  include:
    # - "/docs"       # `docs` under root
    # - "*.md"        # `.md` file in any place
    # - "images/*"    # `images` in any sub folder
  exclude:
    # - "*.tmp"
    # - "/build"      # `build` in root folder